version: '3.8'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    expose:
    - "3000"
    networks:
      - app_network

  app2:
    build: .
    environment:
      - APP_NAME=App2
    expose:
    - "3000"
    networks:
      - app_network

  app3:
    build: .
    environment:
      - APP_NAME=App3
    expose:
    - "3000"
    networks:
      - app_network
  app4:
    build: .
    environment:
      - APP_NAME=App4
    expose:
    - "3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app1
      - app2
      - app3
      - app4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-certs:/etc/nginx/certs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
