version: '3.8'

services:
  app:
    build: ./app        # single app folder
    expose:
      - "3000"          # container internal port only
    networks:
      - app_network
    deploy:
      replicas: 4       # 3 instances of the same app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs:/etc/nginx/certs:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
